2024-06-02 23:21:19,705 ERROR: Exception on /notifications [GET] [in C:\Users\kaike\Desktop\PROGRAMA - OS\venv\Lib\site-packages\flask\app.py:1454]
Traceback (most recent call last):
  File "C:\Users\kaike\Desktop\PROGRAMA - OS\venv\Lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kaike\Desktop\PROGRAMA - OS\venv\Lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kaike\Desktop\PROGRAMA - OS\venv\Lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kaike\Desktop\PROGRAMA - OS\venv\Lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kaike\Desktop\PROGRAMA - OS\venv\Lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\kaike\Desktop\PROGRAMA - OS\app.py", line 725, in notifications
    return render_template('notifications.html', notifications=notifications)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kaike\Desktop\PROGRAMA - OS\venv\Lib\site-packages\flask\templating.py", line 147, in render_template
    return _render(
           ^^^^^^^^
  File "C:\Users\kaike\Desktop\PROGRAMA - OS\venv\Lib\site-packages\flask\templating.py", line 128, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kaike\Desktop\PROGRAMA - OS\venv\Lib\site-packages\jinja2\environment.py", line 1304, in render
    self.environment.handle_exception()
  File "C:\Users\kaike\Desktop\PROGRAMA - OS\venv\Lib\site-packages\jinja2\environment.py", line 939, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "c:\Users\kaike\Desktop\PROGRAMA - OS\templates\notifications.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "c:\Users\kaike\Desktop\PROGRAMA - OS\templates\base.html", line 115, in top-level template code
    {% block content %}{% endblock %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\kaike\Desktop\PROGRAMA - OS\templates\notifications.html", line 8, in block 'content'
    <a href="{{ url_for('clear_notifications') }}" class="btn btn-danger btn-sm">Limpar notificações</a>
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kaike\Desktop\PROGRAMA - OS\venv\Lib\site-packages\flask\helpers.py", line 338, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kaike\Desktop\PROGRAMA - OS\venv\Lib\site-packages\flask\helpers.py", line 325, in url_for
    rv = url_adapter.build(
         ^^^^^^^^^^^^^^^^^^
  File "C:\Users\kaike\Desktop\PROGRAMA - OS\venv\Lib\site-packages\werkzeug\routing.py", line 2305, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'clear_notifications'. Did you mean 'notifications' instead?
2024-06-02 23:28:12,256 ERROR: Exception on /notifications [GET] [in C:\Users\kaike\Desktop\PROGRAMA - OS\venv\Lib\site-packages\flask\app.py:1454]
Traceback (most recent call last):
  File "C:\Users\kaike\Desktop\PROGRAMA - OS\venv\Lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kaike\Desktop\PROGRAMA - OS\venv\Lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kaike\Desktop\PROGRAMA - OS\venv\Lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kaike\Desktop\PROGRAMA - OS\venv\Lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kaike\Desktop\PROGRAMA - OS\venv\Lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\kaike\Desktop\PROGRAMA - OS\app.py", line 725, in notifications
    c.execute('SELECT * FROM notifications WHERE user_id = ? ORDER BY created_at DESC', (current_user.id,))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kaike\Desktop\PROGRAMA - OS\venv\Lib\site-packages\flask\templating.py", line 147, in render_template
    return _render(
           ^^^^^^^^
  File "C:\Users\kaike\Desktop\PROGRAMA - OS\venv\Lib\site-packages\flask\templating.py", line 128, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kaike\Desktop\PROGRAMA - OS\venv\Lib\site-packages\jinja2\environment.py", line 1304, in render
    self.environment.handle_exception()
  File "C:\Users\kaike\Desktop\PROGRAMA - OS\venv\Lib\site-packages\jinja2\environment.py", line 939, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "c:\Users\kaike\Desktop\PROGRAMA - OS\templates\notifications.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "c:\Users\kaike\Desktop\PROGRAMA - OS\templates\base.html", line 115, in top-level template code
    {% block content %}{% endblock %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\kaike\Desktop\PROGRAMA - OS\templates\notifications.html", line 8, in block 'content'
    <a href="{{ url_for('clear_notifications') }}" class="btn btn-danger btn-sm">Limpar notificações</a>
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kaike\Desktop\PROGRAMA - OS\venv\Lib\site-packages\flask\helpers.py", line 338, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kaike\Desktop\PROGRAMA - OS\venv\Lib\site-packages\flask\helpers.py", line 325, in url_for
    rv = url_adapter.build(
         ^^^^^^^^^^^^^^^^^^
  File "C:\Users\kaike\Desktop\PROGRAMA - OS\venv\Lib\site-packages\werkzeug\routing.py", line 2305, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'clear_notifications'. Did you mean 'notifications' instead?
